apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: bookinfo-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/xutao1989103/bookinfo